#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX11.3.sdk                                     # [osx]

c_compiler_version:                                         # [unix]
  - 10.4.0                                                  # [linux]
  - 12.0.1                                                  # [osx]

cxx_compiler_version:                                       # [unix]
  - 10.4.0                                                  # [linux]
  - 12.0.1                                                  # [osx]

fortran_compiler_version:                                   # [unix]
  - 10.4.0                                                  # [linux]
  - 9.3.0                                                   # [not arm64 and osx]
  - 11.0.1                                                  # [arm64]

macos_min_version:                                          # [osx]
  - 11.3                                                    # [osx]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 11.3                                                    # [osx]
