mpi:
  - mpich
  - openmpi

mpi_version:
  - 4.2.1
  - 4.1.6

mpi_friendly_name:
  - MPICH
  - OpenMPI

mpi_website:
  - http://www.mpich.org/documentation/guides
  - https://www.open-mpi.org/doc/

mpi_dev_website:
  - https://github.com/pmodels/mpich
  - https://github.com/open-mpi/ompi

zip_keys:
  - mpi
  - mpi_version
  - mpi_friendly_name
  - mpi_website
  - mpi_dev_website

moose_hdf5:
  - hdf5 1.14.2

moose_libexpat:
  - libexpat 2.5.0

### If you change these versions, change also conda/wasp/*, conda/seacas/*
moose_cmake:
  - cmake 3

### If you change these versions, change also conda/wasp/*, conda/seacas/*
moose_cc:
  - gcc 12.3.0 h915e2ae_13                                  # [linux]
  - clang 16.0.6 default_h420b035_14                        # [not arm64 and osx]
  - clang 16.0.6 default_h87a6e52_14                        # [arm64]

### If you change these versions, change also conda/wasps/*, conda/seacas/*
moose_cxx:
  - gxx 12.3.0 h915e2ae_13                                  # [linux]
  - clangxx 16.0.6 default_h2725d3a_14                      # [not arm64 and osx]
  - clangxx 16.0.6 default_h75e0ad0_14                      # [arm64]

### If you change these versions, change also conda/seacas/*
moose_gfortran:
  - gfortran 12.3.0 h915e2ae_13                             # [linux]
  - gfortran 12.4.0 hcc3c99d_1                              # [not arm64 and osx]
  - gfortran 12.4.0 h3ef1dbf_1                              # [arm64]

### Cmake requires these be installed in order to "find" compilers
moose_ccompiler:
  - gcc_linux-64                                            # [linux]
  - clang_osx-64                                            # [not arm64 and osx]
  - clang_osx-arm64                                         # [arm64]

moose_cxxcompiler:
  - gxx_linux-64                                            # [linux]
  - clangxx_osx-64                                          # [not arm64 and osx]
  - clangxx_osx-arm64                                       # [arm64]

moose_libgfortran5:
  - libgfortran5 14.2.0 hf1ad2bd_2                          # [linux]
  - libgfortran5 14.2.0 h58528f3_105                        # [not arm64 and osx]
  - libgfortran5 14.2.0 h2c44a93_105                        # [arm64]

moose_gcc_impl:                                             # [linux]
  - gcc_impl_linux-64 12.3.0 h58ffeeb_13                     # [linux]

moose_gfortran_impl:                                        # [linux]
  - gfortran_impl_linux-64 12.3.0 h8f2110c_13                # [linux]

### Below are pinings created at the time of render
### based on above content. If any of the above
### content changes, modification will be needed below
moose_libstdcxx:                                            # [linux]
  - libstdcxx 14.2.0 h8f9b012_2                             # [linux]

moose_libstdcxx_devel:                                      # [linux]
  - libstdcxx-devel_linux-64 12.3.0 h6b66f73_113            # [linux]

moose_libcxx:
  - libcxx 20.1.2 ha0f52bf_0                                # [linux]
  - libcxx 20.1.2 hf95d169_0                                # [not arm64 and osx]
  - libcxx 20.1.2 ha82da77_0                                # [arm64]

moose_libzlib:
  - libzlib 1.3.1 h4ab18f5_1                                # [linux]
  - libzlib 1.3.1 hd23fc13_2                                # [not arm64 and osx]
  - libzlib 1.3.1 h8359307_2                                # [arm64]

moose_icu:
  - icu 73.2 h59595ed_0                                     # [linux]
  - icu 73.2 hf5e326d_0                                     # [not arm64 and osx]
  - icu 73.2 hc8870d7_0                                     # [arm64]

moose_cctools:                                              # [osx]
  - cctools_osx-64 1010.6 heaa7f0c_1                        # [not arm64 and osx]
  - cctools_osx-arm64 1010.6 h4f2c9d0_1                     # [arm64]

moose_compiler_rt:                                          # [osx]
  - compiler-rt 16.0.6 ha38d28d_2                           # [not arm64 and osx]
  - compiler-rt 16.0.6 h3808999_2                           # [arm64]

moose_clang_osx:                                            # [osx]
  - clangxx_osx-64 16.0.6 hb91bd55_19                       # [not arm64 and osx]
  - clang_osx-arm64 16.0.6 h54d7cd3_19                      # [arm64]

moose_llvm_openmp:                                          # [osx]
  - llvm-openmp 20.1.2 ha54dae1_0                           # [not arm64 and osx]
  - llvm-openmp 20.1.2 hdb05f8b_0                           # [arm64]

moose_llvm_tools:                                           # [osx]
  - llvm-tools 16.0.6 hbedff68_3                            # [not arm64 and osx]
  - llvm-tools 16.0.6 haab561b_3                            # [arm64]

moose_libclang:
  - libclang13 15.0.7 default_h5d6823c_5                    # [linux]
  - libclang-cpp16 16.0.6 default_he1224e2_14               # [not arm64 and osx]
  - libclang-cpp16 16.0.6 default_hc2ef00a_14               # [arm64]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX11.3.sdk                                     # [osx]

macos_min_version:                                          # [osx]
  - 11.3                                                    # [osx]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 11.3                                                    # [osx]
