mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2025.04.02 mpich_1
  - moose-libmesh 2025.04.02 openmpi_1

moose_wasp:
  - moose-wasp 2025.02.25

moose_tools:
  - moose-tools 2025.03.31

moose_peacock:
  - moose-peacock 2025.03.31

zip_keys:
  - mpi
  - moose_libmesh
